# Generated by Django 4.2.1 on 2023-05-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Password', models.CharField(max_length=500)),
                ('LastLogin', models.DateTimeField(null=True)),
                ('DateAdded', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
    ]
