# Generated by Django 4.2.1 on 2023-05-25 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('patients', '0002_alter_patients_patientsno'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Triage', models.CharField(max_length=2000)),
                ('dateAdded', models.DateTimeField(auto_now=True)),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.registration')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
            options={
                'db_table': 'patientRecords',
            },
        ),
    ]
