# Generated by Django 4.2.1 on 2023-05-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='PatientsNo',
            field=models.CharField(max_length=255),
        ),
    ]
